# Generated by Django 3.2.4 on 2021-06-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(max_length=100, unique=True)),
                ('superpower1', models.TextField()),
                ('superpower2', models.TextField()),
                ('weakness1', models.TextField()),
                ('weakness2', models.TextField()),
                ('hero_age', models.IntegerField()),
                ('gender', models.TextField(choices=[('Female', 'FEMALE'), ('Male', 'MALE')], default='Male')),
                ('secret_identity', models.CharField(max_length=255)),
            ],
        ),
    ]
