# Generated by Django 3.2.4 on 2021-06-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='gender',
            field=models.CharField(choices=[('Female', 'FEMALE'), ('Male', 'MALE')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='superpower1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='superpower2',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='weakness1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='weakness2',
            field=models.CharField(max_length=25),
        ),
    ]
